### ISSUE TITLE
Plex - Cannot be updated.

### ISSUE THREAD

**Issue by HerrDerMelonen** [BackInBash/moby-plex#1]
If I want to update Plex via the Dogger Container it is not possible because it will stay on the same version after it has finished updating. Used Version 1.19.3.2843

![plex-update](https://user-images.githubusercontent.com/49483818/83305968-007c4580-a202-11ea-92ab-ce1e65b34d7d.gif)

**Comment by BackInBash** [comment]
abgelehnt weil völlig albern
