### ISSUE TITLE
Plex Media Server

### ISSUE THREAD

**Issue by BackInBash** [BackInBash/moby-plex#3]
Plex Media Server analysierern und dokumentieren.

+ Dokumentation der Pfade & Registry Keys
+ Erstellen einer Migrationsanleitung
+ Erstellen eines Updatepfads

**Comment by HerrDerMelonen** [comment]
## Dokumentation der Pfade & Registry Keys
* Alle erforderlichen Registry Keys für den Plex Media Server sind hier zu finden: 

**Regestry Location:**
```text
HKEY_CURRENT_USER\Software\Plex, Inc.\Plex Media Server
```

**Powerschnell reg export:**
```powershell
reg export 'HKCU\Software\Plex, Inc.\Plex Media Server' Plex.reg
```

**Powerschnell reg Import:**
```powershell
reg import Plex.reg
.
.
.
Wer hätts gedacht ¯\_(ツ)_/¯
``` 
* Quelle: https://support.plex.tv/articles/201539237-backing-up-plex-media-server-data/ 

## Erstellen einer Migrationsanleitung

Die Erklärung ist nur für bereits existierende Plex Media Server Installation ausgelegt die auf ein anderes System migriert wird.

**Vorbereitung**

1. Folgende Einstellung Deaktivieren. Einstellungen > Mediathek > Papierkorb nach jedem Scan automatisch leeren.
(Verhindert das automatische löschen der Medien, wenn Plex auf dem neuen Server wieder gestartet wird)
2. Installation von Plex Media Server auf dem neuen Ziel Server. (Bei der Einrichtung von Plex im Browser abrechen und Browser Fenster schließen.)
3. Auf dem aktuellem Server vom Plex Server abmelden und Plex Stoppen.

**Plex Data Kopieren**

1. Plex Data vom aktuellen Server auf den neuen Plex Server Kopieren. (Der Ordner "Cache" kann bei Bedarf weggelassen werden, um Speicher zu sparen.)

**Plex Data directory:**

```text
%LOCALAPPDATA%\Plex Media Server
```

**Neu Einbindung des Plex Servers**
1. Nach dem die Plex Data erfolgreich kopiert wurde kann der Plex Server gestartet werden.
2. Am neuen Plex Server wieder Anmelden.
3. Pfad der Mediatheken neu einbinden.
4. Falls nicht schon automatisch geschehen eine Media Scan durchführen.
5. Folgende Einstellung wieder aktivieren. Einstellungen > Mediathek > Papierkorb nach jedem Scan automatisch leeren.

* Quelle: https://support.plex.tv/articles/201370363-move-an-install-to-another-system/
* Quelle: https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/


## ~~Erstellen eines Updatepfads~~
## Verbesserungen/Enhancement

Es ist möglich unter Windows per Regestry einen Custom Pfad zur Plex Data anzugeben (%LOCALAPPDATA%\Plex Media Server)

**LocalAppDataPath** |
-------------------- |
**Wert:** Pfad       |
**Beschreibung:** Legt den Speicherort des Plex Media Server Datenverzeichnisses fest (Windows only).|
**Beispiel:** D:\Data\PlexData |

* Quelle: https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/

**Comment by BackInBash** [comment]
Plex Docker Container angepasst.
